Repository BF-FrontEnd-class-2025/group-2-hyf, pull requests merged in 2025-01, with the labels that each got.

#9 project definination
  README.md
Labels: md

#11 add communication
  planning/communication.md
Labels: md, description

#12 add user personas
  planning/user-personas.md
Labels: md, description

#13 add backlog
  planning/backlog.md
Labels: md, description

#14 add design
  .cspell.json
  planning/backlog.md
  planning/design-hyf.png
  planning/design.md
Labels: md, description

#28 add html and css
  index.html
Labels: html, css

#29 add project review
  README.md
  planning/retrospective.md
  planning/screenshot-1.png
  planning/screenshot-2.png
  planning/screenshot-3.png
Labels: md, description

#31 Adjust readme
  README.md
  index.html
  planning/development-strategy.md
Labels: md, description

#33 adjust readme2
  README.md
Labels: md, description
